# @name createEmployee1
PUT http://localhost:3000/employees
Content-Type: application/json

{
  "Id": 10503058,
  "TenantId": 10029872,
  "CompanyId": 10028636,
  "EmployeeCode": "653",
  "FirstNames": "Hendrik", 
  "LastName": "De Voogd",
  "LastNameAtBirth": "Voogd",
  "Initials": "A.H.",
  "LastNameAtBirthPrefix": "de",
  "EmploymentIndicator": "1"
}

###
# @name updateEmployee
POST http://localhost:3000/employees/10503058
Content-Type: application/json

{
  "EmploymentIndicator": "2"
}

###
# @name createEmployee2
PUT http://localhost:3000/employees
Content-Type: application/json

{
  "Id": 10503060,
  "TenantId": 10029872,
  "CompanyId": 10028636,
  "EmployeeCode": "688",
  "FirstNames": "Joop", 
  "LastName": "Janssen",
  "LastNameAtBirth": "Janssen",
  "Initials": "J.P.",
  "EmploymentIndicator": "1"
}