# @name createEmployee
PUT http://localhost:3000/employees
Content-Type: application/json

{
  "CompanyId": 3,
  "FirstNames":"John", 
  "LastName":"Doo",
  "EmploymentIndicator":"1",
  "MobilePhoneNumber":"0612345678",
  "Language":"EN"
}

###
@employeeId = {{createEmployee.response.body.$.id}}

# @name updateEmployee
POST http://localhost:3000/employees/{{employeeId}}
Content-Type: application/json

{
  "FirstNames":"Johhny",
  "LastName":"Depp",
  "EmploymentIndicator":"2"
}