version: '3.8'
services:
  readapi:
    build:
      context: ./ReadApi
      dockerfile: ./Dockerfile
    ports:
      - '2000:80'
    depends_on:
      - rodb
  writeapi:
    build: 
      context: ./WriteApi
      dockerfile: ./Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - eavdb
  eavdb:
    build:
      context: ./EavDb
      dockerfile: ./Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=verySecure(!)Password
    ports:
      - '1433:1433'
  rodb:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=rodb
      - MONGO_INITDB_ROOT_USERNAME=rodb
      - MONGO_INITDB_ROOT_PASSWORD=rodb
    ports:
      - '27017-27019:27017-27019'
  mutationstore:
    image: 'mcr.microsoft.com/azure-storage/azurite'
    ports:
      - '10000-10001:10000-10001'
  mutationextractor:
    build:
      context: ./MutationExtractor
      dockerfile: ./Dockerfile
    depends_on:
      - eavdb
      - mutationstore
  mutationprocessor:
    build:
      context: ./MutationProcessor
      dockerfile: ./Dockerfile
    depends_on:
      - mutationstore
      - rodb