version: '3'
services:
  readapi:
    build: ./ReadApi/
    ports:
      - '2000:80'
  writeapi:
    build: ./WriteApi/
    ports:
      - '3000:80'
  eavdb:
    build: ./EavDb/
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=verySecure(!)Password
    ports:
      - '1433:1433'
  rodb:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=rodb
      - MONGO_INITDB_ROOT_USERNAME=rodb
      - MONGO_INITDB_ROOT_PASSWORD=rodb
    ports:
      - '27017-27019:27017-27019'
  mutationstore:
    image: 'mcr.microsoft.com/azure-storage/azurite'
    ports:
      - '10000-10001:10000-10001'