version: '3.8'
services:
  readapi:
    build:
      context: ./ReadApi
      dockerfile: ./Dockerfile
    ports:
      - '2000:80'
    depends_on:
      - rodb
  writeapi:
    build: 
      context: ./WriteApi
      dockerfile: ./Dockerfile
    environment:
      - SQL_CONNECTIONSTRING=Server=host.docker.internal,1433;Database=EavDb;User Id=sa;Password=verySecure(!)Password;
    ports:
      - '3000:80'
    depends_on:
      - eavdb
  eavdb:
    build:
      context: ./EavDb
      dockerfile: ./Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=verySecure(!)Password
    ports:
      - '1433:1433'
  rodb:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=rodb
      - MONGO_INITDB_ROOT_USERNAME=rodb
      - MONGO_INITDB_ROOT_PASSWORD=rodb
    ports:
      - '27017-27019:27017-27019'
  mutationstore:
    image: 'mcr.microsoft.com/azure-storage/azurite'
    ports:
      - '10000-10001:10000-10001'
    environment:
      - AZURITE_ACCOUNTS=eavtonosql:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
  mutationextractor:
    build:
      context: ./MutationExtractor
      dockerfile: ./Dockerfile
    depends_on:
      - eavdb
      - mutationstore
    environment:
      - SQL_CONNECTIONSTRING=Server=host.docker.internal,1433;Database=EavDb;User Id=sa;Password=verySecure(!)Password;
      # Notice: I'm using 127.0.0.1 here due to a weird behavior inside the client for Azure Queue. This is fixed on runtime (ContainerQueueClient) 
      - QUEUE_CONNECTIONSTRING=DefaultEndpointsProtocol=http;AccountName=eavtonosql;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/eavtonosql;QueueEndpoint=http://127.0.0.1:10001/eavtonosql;
      - QUEUE_NAME=changes
  mutationprocessor:
    build:
      context: ./MutationProcessor
      dockerfile: ./Dockerfile
    depends_on:
      - mutationstore
      - rodb
    environment:
      - MONGO_CONNECTIONSTRING=mongodb://rodb:rodb@host.docker.internal:27017
      # Notice: I'm using 127.0.0.1 here due to a weird behavior inside the client for Azure Queue. This is fixed on runtime (ContainerQueueClient) 
      - QUEUE_CONNECTIONSTRING=DefaultEndpointsProtocol=http;AccountName=eavtonosql;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/eavtonosql;QueueEndpoint=http://127.0.0.1:10001/eavtonosql;
      - QUEUE_NAME=changes