version: '3'
services:
  eavdb:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    container_name: 'eavdb'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - '1433:1433'